package ee.sda.entities;

import javax.persistence.*;
import java.util.List;
import java.util.Objects;

@Entity
@Table(name = "vaccine")

public class Vaccine {

    @Id     //used for column with primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)  //the value will be generated by the db
    @Column(name = "vaccine_id")
    private int vaccine_id;

    @Column(name = "vaccine_name")
    private String vaccine_name;

    @Column(name = "vaccine_description")
    private String vaccine_description;

    @ManyToMany(mappedBy = "vaccines")
    private List<Pet> pets;

    public Vaccine(String vaccine_name, String vaccine_description) {
        this.vaccine_name = vaccine_name;
        this.vaccine_description = vaccine_description;
    }

    public Vaccine() {
    }

    public int getId() {
        return vaccine_id;
    }

    public void setId(int vaccine_id) {
        this.vaccine_id = vaccine_id;
    }

    public String getVaccine_name() {
        return vaccine_name;
    }

    public void setVaccine_name(String vaccine_name) {
        this.vaccine_name = vaccine_name;
    }

    public String getVaccine_description() {
        return vaccine_description;
    }

    public void setVaccine_description(String vaccine_description) {
        this.vaccine_description = vaccine_description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Vaccine vaccine = (Vaccine) o;
        return getId() == vaccine.getId() &&
                Objects.equals(getVaccine_name(), vaccine.getVaccine_name()) &&
                Objects.equals(getVaccine_description(), vaccine.getVaccine_description());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getVaccine_name(), getVaccine_description());
    }

    @Override
    public String toString() {
        return "Vaccine{" +
                "vaccine_id=" + vaccine_id +
                ", vaccine_name='" + vaccine_name + '\'' +
                ", vaccine_description='" + vaccine_description + '\'' +
                '}';
    }


}